### PR TITLE
Restructure and improve docs around txacme use.

### PR DESCRIPTION
**Pull request by jonathanj**
In particular, improve the clarity of the server endpoint string
documentation.

---
This change is [Reviewable](https://reviewable.io/reviews/mithrandi/txacme/48)

### CODE REVIEW

**Comment by mithrandi** [comment]
Reviewed 2 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[docs/using.rst, line 4 \[r1\]](https://reviewable.io:443/reviews/mithrandi/txacme/48#-KNWwSKZJv0grtBblVig:-KNWwSK_eOe3ROEsPKzL:-1408459738) ([raw file](https://github.com/mithrandi/txacme/blob/d15ea259f67494d9c9921d569b4cec199c27d949/docs/using.rst#L4)):*
> ```reStructuredText
> ============
> 
> There are several possible ways to make use of txacme, from a simple endpoint.
> ```

"from a simple endpoint" doesn't seem to make sense as an ending to this sentence. I think you have some missing or incorrect words here, can't tell which.

---

*[docs/using.rst, line 15 \[r1\]](https://reviewable.io:443/reviews/mithrandi/txacme/48#-KNPiSXORF5yRLGBWHTX:-KNPiSXP-thTGAKWKsrA:2068098605) ([raw file](https://github.com/mithrandi/txacme/blob/d15ea259f67494d9c9921d569b4cec199c27d949/docs/using.rst#L15)):*
> ```reStructuredText
> to store certificates in, and the underlying endpoint to listen on. One might
> use the following command to start a Twisted web server on TCP port 443 and
> store certificates in the `/srv/www/certs` directory:
> ```

You need double backquotes here (single backquotes get you a reference).

---

*[docs/using.rst, line 88 \[r1\]](https://reviewable.io:443/reviews/mithrandi/txacme/48#-KNWy-pqhaOMaMuWbUun:-KNWy-pqhaOMaMuWbUuo:-296582445) ([raw file](https://github.com/mithrandi/txacme/blob/d15ea259f67494d9c9921d569b4cec199c27d949/docs/using.rst#L88)):*
> ```reStructuredText
> The `.ICertificateStore` and `.IResponder` interfaces are the main extension
> points for using the issuing service directly. For example, a custom
> implementation might manage the certificate configuration of a cloud load
> ```

I know this is my wording originally, but how about expanding this to "a custom implementation of `.ICertificateStore`" since it seems a bit unclear?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mithrandi/txacme/48)*

**Comment by mithrandi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mithrandi/txacme/48)*

**Comment by jonathanj** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[docs/using.rst, line 4 \[r1\]](https://reviewable.io:443/reviews/mithrandi/txacme/48#-KNWwSKZJv0grtBblVig:-KNlQdnvF_9AsJjdifQk:-1792733512) ([raw file](https://github.com/mithrandi/txacme/blob/d15ea259f67494d9c9921d569b4cec199c27d949/docs/using.rst#L4)):*
<details><summary><i>Previously, mithrandi (Tristan Seligmann) wrote…</i></summary>
> "from a simple endpoint" doesn't seem to make sense as an ending to this sentence. I think you have some missing or incorrect words here, can't tell which.
</details>
Sorry, I started writing this and forgot to finish it. It's done now. The thinking here was to give a brief overview (even though there's a bit of duplication in the specialised sections) of the possible ways to use txacme.

---

*[docs/using.rst, line 15 \[r1\]](https://reviewable.io:443/reviews/mithrandi/txacme/48#-KNPiSXORF5yRLGBWHTX:-KNlQrUUMltPGxT3gpjv:-499146009) ([raw file](https://github.com/mithrandi/txacme/blob/d15ea259f67494d9c9921d569b4cec199c27d949/docs/using.rst#L15)):*
<details><summary><i>Previously, mithrandi (Tristan Seligmann) wrote…</i></summary>
> You need double backquotes here (single backquotes get you a reference).
</details>
Done.

---

*[docs/using.rst, line 88 \[r1\]](https://reviewable.io:443/reviews/mithrandi/txacme/48#-KNWy-pqhaOMaMuWbUun:-KNlQs2M-KkCzN6cX42E:-499146009) ([raw file](https://github.com/mithrandi/txacme/blob/d15ea259f67494d9c9921d569b4cec199c27d949/docs/using.rst#L88)):*
<details><summary><i>Previously, mithrandi (Tristan Seligmann) wrote…</i></summary>
> I know this is my wording originally, but how about expanding this to "a custom implementation of `.ICertificateStore`" since it seems a bit unclear?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mithrandi/txacme/48)*

**Comment by mithrandi** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mithrandi/txacme/48)*

**Pull request merged**
