### PR TITLE
Add an issue_cert method to AcmeIssuingService

### LINKED ISSUE #76: Issuing service API for issuing a new certificate on demand
It's currently only possible to add/remove certificates from txacme by touching/deleting certificate files in the certificate directory (or adding/removing from some other store implementation).

It's technically possible to directly store empty certificates in an `ICertificateStore` and then call the `AcmeIssuingService._check_certs()` but that is messy and may be prone to race conditions with the timed invocation of the same method.

It should be possible to safely add and remove certificates from txacme.

A further iteration on this is perhaps the ability to _modify_ certificates, e.g. to change (or as it is described in the certbot client, _"expand"_) the SANs (#37).

### PR DESCRIPTION
**Pull request by mithrandi**
Fixes #76.

---
This change is [Reviewable](https://reviewable.io/reviews/mithrandi/txacme/78)

### CODE REVIEW

**Comment by jerith** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/txacme/service.py, line 75 at r1](https://reviewable.io:443/reviews/mithrandi/txacme/78#-KUqhyqx6Fnpd0wpqnjm:-KUqhyqx6Fnpd0wpqnjn:b4b1h28) ([raw file](https://github.com/mithrandi/txacme/blob/bb75f456a541ee0c614d96f861c87f46e44681af/src/txacme/service.py#L75)):*
> ```Python
> 
>     _waiting = attr.ib(default=attr.Factory(list), init=False)
>     _issuing = attr.ib(default=attr.Factory(dict), init=False)
> ```

Why the extra `init=False` here?  Is it something that should really have been there all along?

---

*[src/txacme/service.py, line 163 at r1](https://reviewable.io:443/reviews/mithrandi/txacme/78#-KUqk3Yzb64vJXfSKZB0:-KUqk3Z-FjhQvD_gSMu4:bn6ns5c) ([raw file](https://github.com/mithrandi/txacme/blob/bb75f456a541ee0c614d96f861c87f46e44681af/src/txacme/service.py#L163)):*
> ```Python
>         d = Deferred(lambda _: d_issue.cancel())
>         if server_name in self._issuing:
>             d_issue, waiting = self._issuing[server_name]
> ```

Do we need `d_issue` here? Nothing in this branch (or after) uses it.

---

*[src/txacme/testing.py, line 83 at r1](https://reviewable.io:443/reviews/mithrandi/txacme/78#-KUqpd4Q629x2kTC20lM:-KUqpd4Q629x2kTC20lN:b-njb432) ([raw file](https://github.com/mithrandi/txacme/blob/bb75f456a541ee0c614d96f861c87f46e44681af/src/txacme/testing.py#L83)):*
> ```Python
>         self._waiting = []
>         if controller is None:
>             controller = FakeClientController()
> ```

We currently only create a `FakeClient` in one place and we pass in a controller. Would it make sense to simplify this constructor and either always create the controller internally (and grab it from the client where we need it) or always pass one in?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mithrandi/txacme/78)*

**Comment by mithrandi** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/txacme/service.py, line 75 at r1](https://reviewable.io:443/reviews/mithrandi/txacme/78#-KUqhyqx6Fnpd0wpqnjm:-KUqr1ZHWlB-0A0djiOq:b-i49u5s) ([raw file](https://github.com/mithrandi/txacme/blob/bb75f456a541ee0c614d96f861c87f46e44681af/src/txacme/service.py#L75)):*
<details><summary><i>Previously, jerith (Jeremy Thurgood) wrote…</i></summary>
> Why the extra `init=False` here?  Is it something that should really have been there all along?
</details>
It's an incompatible change to the signature of __init__ but I think being able to pass in a value for `waiting` makes no sense and is very confusing. I think when I wrote this code originally, `attrs` hadn't yet added support for `default=...` combined with `init=False`, so that may be why I originally didn't have it that way.

---

*[src/txacme/service.py, line 163 at r1](https://reviewable.io:443/reviews/mithrandi/txacme/78#-KUqk3Yzb64vJXfSKZB0:-KUqrHabtDy62vePbbEE:bycq1uu) ([raw file](https://github.com/mithrandi/txacme/blob/bb75f456a541ee0c614d96f861c87f46e44681af/src/txacme/service.py#L163)):*
<details><summary><i>Previously, jerith (Jeremy Thurgood) wrote…</i></summary>
> Do we need `d_issue` here? Nothing in this branch (or after) uses it.
</details>
The code that uses it is in fact located _before_ this branch; it's the lambda passed as the canceller two lines up. That's admittedly a little confusing, but I didn't want to duplicate the instantiation of the `Deferred` and both branches need it.

---

*[src/txacme/testing.py, line 83 at r1](https://reviewable.io:443/reviews/mithrandi/txacme/78#-KUqpd4Q629x2kTC20lM:-KUqrgHV8oKFPBxvIUUK:b-qw71ef) ([raw file](https://github.com/mithrandi/txacme/blob/bb75f456a541ee0c614d96f861c87f46e44681af/src/txacme/testing.py#L83)):*
<details><summary><i>Previously, jerith (Jeremy Thurgood) wrote…</i></summary>
> We currently only create a `FakeClient` in one place and we pass in a controller. Would it make sense to simplify this constructor and either always create the controller internally (and grab it from the client where we need it) or always pass one in?
</details>
We actually create a `FakeClient` in three places (by my count: `test_endpoint`, `test_client`, and the integration tests), and two of them don't currently need the controller functionality.

Grabbing the controller from the client is problematic, because the real client of course doesn't have such an attribute; relying on "testing only" APIs makes it easier to accidentally introduce a bug by writing code that only works with the test double, but not the real implementation. That's the usual argument against doing this, anyway...

Always passing one sounds reasonable, though; explicit is better than implicit, or something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mithrandi/txacme/78)*

**Comment by jerith** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/txacme/service.py, line 75 at r1](https://reviewable.io:443/reviews/mithrandi/txacme/78#-KUqhyqx6Fnpd0wpqnjm:-KUqzqNz_6njO4P76Dc-:bmxyqkd) ([raw file](https://github.com/mithrandi/txacme/blob/bb75f456a541ee0c614d96f861c87f46e44681af/src/txacme/service.py#L75)):*
<details><summary><i>Previously, mithrandi (Tristan Seligmann) wrote…</i></summary>
> It's an incompatible change to the signature of __init__ but I think being able to pass in a value for `waiting` makes no sense and is very confusing. I think when I wrote this code originally, `attrs` hadn't yet added support for `default=...` combined with `init=False`, so that may be why I originally didn't have it that way.
</details>
OK, thanks for the explanation.

---

*[src/txacme/service.py, line 163 at r1](https://reviewable.io:443/reviews/mithrandi/txacme/78#-KUqk3Yzb64vJXfSKZB0:-KUr-QmCBUalq1uvre3A:bq2i2bj) ([raw file](https://github.com/mithrandi/txacme/blob/bb75f456a541ee0c614d96f861c87f46e44681af/src/txacme/service.py#L163)):*
<details><summary><i>Previously, mithrandi (Tristan Seligmann) wrote…</i></summary>
> The code that uses it is in fact located _before_ this branch; it's the lambda passed as the canceller two lines up. That's admittedly a little confusing, but I didn't want to duplicate the instantiation of the `Deferred` and both branches need it.
</details>
Maybe a brief comment or something (either here or above) would help?

---

*[src/txacme/testing.py, line 83 at r1](https://reviewable.io:443/reviews/mithrandi/txacme/78#-KUqpd4Q629x2kTC20lM:-KUr-f9TOp-Z_8fNfd_1:b-eev15j) ([raw file](https://github.com/mithrandi/txacme/blob/bb75f456a541ee0c614d96f861c87f46e44681af/src/txacme/testing.py#L83)):*
<details><summary><i>Previously, mithrandi (Tristan Seligmann) wrote…</i></summary>
> We actually create a `FakeClient` in three places (by my count: `test_endpoint`, `test_client`, and the integration tests), and two of them don't currently need the controller functionality.
> 
> Grabbing the controller from the client is problematic, because the real client of course doesn't have such an attribute; relying on "testing only" APIs makes it easier to accidentally introduce a bug by writing code that only works with the test double, but not the real implementation. That's the usual argument against doing this, anyway...
> 
> Always passing one sounds reasonable, though; explicit is better than implicit, or something?
</details>
I didn't find those other places. Given that they exist, though, the slight extra complexity involved in making this optional is almost certainly worthwhile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mithrandi/txacme/78)*

**Comment by mithrandi** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/txacme/service.py, line 163 at r1](https://reviewable.io:443/reviews/mithrandi/txacme/78#-KUqk3Yzb64vJXfSKZB0:-KV0WYZCZsWU10Hyff8N:b-896fix) ([raw file](https://github.com/mithrandi/txacme/blob/bb75f456a541ee0c614d96f861c87f46e44681af/src/txacme/service.py#L163)):*
<details><summary><i>Previously, jerith (Jeremy Thurgood) wrote…</i></summary>
> Maybe a brief comment or something (either here or above) would help?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mithrandi/txacme/78)*

**Comment by jerith** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mithrandi/txacme/78#-:-KV0X2D5lZ4qRFxx9BoH:bnfp4nl)*

**Pull request merged**
