### PR TITLE
Retry POST requests that fail with a badNonce error

### LINKED ISSUE #66: Retry `badNonce` errors directly
The overall error handling logic should mean that these errors are not fatal, but we ought to be able to retry immediately with the fresh nonce, which will make things a little more reliable.

### PR DESCRIPTION
**Pull request by jerith**
Fixes #66.

### CODE REVIEW

**Comment by mithrandi** [comment]
This change is [Reviewable](https://reviewable.io/reviews/mithrandi/txacme/95)

**Comment by JayH5** [comment]
:heart: @jerith I was just about to look into this.. currently seeing this error often.

**Comment by mithrandi** [comment]
@JayH5 Are you able to quantify "often" more precisely? I've seen sporadic complaints about this from various people, and it should be a pretty rare occurrence even without this branch, so I'm wondering if there's some underlying bug in either txacme or Boulder that is causing it to occur more often.

(Basically, the only scenario I'm aware of that should cause it is when Boulder is restarted for an upgrade, invalidating all extant nonces)

**Comment by mithrandi** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/txacme/client.py, line 886 at r2](https://reviewable.io:443/reviews/mithrandi/txacme/95#-KX6-KpBCXVmjeiago7B:-KX6-KpBCXVmjeiago7C:b-bq1ans) ([raw file](https://github.com/mithrandi/txacme/blob/8e34e4819107e3a8dbffc2bf0df2447937ffc719/src/txacme/client.py#L886)):*
> ```Python
>         def retry_bad_nonce(f):
>             f.trap(ServerError)
>             if f.value.message.typ.split(':')[-1] == 'badNonce':
> ```

The latest ACME RFC defines the errors in the `urn:ietf:params:acme:error:` namespace. In some earlier drafts (and in what Boulder actually implements), the namespace is `urn:acme:` instead. I assume this is why you have this slightly fuzzy comparison here, which I think is fine, but can you also add a comment explaining this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mithrandi/txacme/95)*

**Comment by JayH5** [comment]
@mithrandi our software is very... *beta*... but I've had a thing running trying to issue a certificate for a domain over the weekend. We're currently hitting the LE rate limit, though, so it's been failing consistently. We get a `rateLimited` error most of the time but sometimes it is a `badNonce` one instead. Admittedly this is a bit of a weird test but I have numbers based on the logs.

* Running for just less than 3 days (2016-11-18T15:18:34+0000 -> 2016-11-21T11:43:57+0000)
* 279 attempts to issue the cert
* 232 `rateLimited` errors
* 47 `badNonce` errors (~17%)

**Comment by mithrandi** [comment]
Hmm, I don't think there were any LE Boulder upgrades in that timeframe.

**Comment by mithrandi** [comment]
After chatting with some LE people, it seems nonces also expire after some time, so that makes it very likely that you'd run into these errors in a long-running txacme-using process. This PR should solve that :tada:

**Comment by mithrandi** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/mithrandi/txacme/95#-KX66M9kimxgNI7-kmxs:-KX66M9kimxgNI7-kmxt:bok3oue) (no related file):*
@jerith: One other thing, could you add a news fragment? This seems changelog-worthy in light of the above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mithrandi/txacme/95)*

**Comment by jerith** [comment]
> After chatting with some LE people, it seems nonces also expire after some time, so that makes it very likely that you'd run into these errors in a long-running txacme-using process. This PR should solve that 🎉

I don't think it would, because we'd still have a bunch of old nonces and we'd likely try one of those next. Maybe we should expire nonces on our side or just clear them all on a `badNonce` error?

**Comment by mithrandi** [comment]
Hmm, I was thinking there would only ever be one nonce, but you can actually get more than one nonce when making concurrent requests. Clearing them all sounds like a reasonable idea; at worst, you're incurring an needless roundtrip to fetch a new initial nonce, which isn't a big deal given all of the other inherent latencies here.

**Comment by jerith** [comment]
Hrm. I missed that we're only (passively) getting nonces from requests that themselves use nonces. Ideally, we'd clear all nonces except the one we just received, but the code for that would be awkward.

**Comment by mithrandi** [comment]
Reviewed 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mithrandi/txacme/95)*

**Pull request merged**
